# Generated by Django 6.0.8 on 2026-09-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_remove_leasecontract_owner_remove_salecontract_owner_and_more'),
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_contract__isnull', False), ('sale_contract__isnull', True)), models.Q(('lease_contract__isnull', True), ('sale_contract__isnull', False)), _connector='OR'), name='schedule_linked_to_exactly_one_contract'),
        ),
    ]
