# Generated by Django 6.0.8 on 2026-09-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_capability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capability',
        ),
    ]
