# Generated by Django 6.0.8 on 2026-09-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='unique_prospect_phone_per_organization'),
        ),
    ]
