"""
Django settings for dahoo project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("La variable d'environnement SECRET_KEY est obligatoire (voir .env.example).")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

AUTH_USER_MODEL = "users.User"

# Clé partagée avec le serveur Next.js : lui seul peut transmettre l'IP réelle des visiteurs
# (voir dahoo/throttling.py). Vide = aucune requête n'est considérée comme venant du front.
INTERNAL_PROXY_KEY = os.getenv("INTERNAL_PROXY_KEY", "")

# Durée de l'essai gratuit d'une nouvelle organisation (jours)
TRIAL_DAYS = int(os.getenv("TRIAL_DAYS", "30"))

AUTHENTICATION_BACKENDS = [
    "users.auth_backends.PhoneBackend",
]


# Application definition

INSTALLED_APPS = [
    "users",
    "organizations",
    "access",
    "properties",
    "leases",
    "payments",
    "maintenance",
    "listings",
    "subscriptions",
    "notifications",
    "field_ops",
    "analytics",
    "public",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dahoo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dahoo.wsgi.application'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "dahoo.throttling.AnonRateThrottle",
        "dahoo.throttling.UserRateThrottle",
        "dahoo.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON", "60/min"),
        "user": os.getenv("THROTTLE_USER", "600/min"),
        "login": os.getenv("THROTTLE_LOGIN", "10/min"),
        "public_interest": os.getenv("THROTTLE_PUBLIC_INTEREST", "10/hour"),
        "demo_request": os.getenv("THROTTLE_DEMO_REQUEST", "5/hour"),
    },
    # Filtres (django-filter), ?search= et ?ordering= : actifs sur les vues qui les déclarent.
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "dahoo.filters.SearchFilter",
        "dahoo.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "dahoo.exceptions.api_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Dahoo API",
    "DESCRIPTION": (
        "API de gestion immobilière. Authentification : POST /api/v1/users/login/ puis "
        "en-tête `Authorization: Bearer <access>`. Si l'utilisateur appartient à plusieurs "
        "organisations, préciser l'en-tête `X-Organization-ID`."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Schémas distincts pour les requêtes (sans champs en lecture seule) : types exacts côté front.
    "COMPONENT_SPLIT_REQUEST": True,
    # Noms explicites des énumérations "status" (sinon suffixes aléatoires dans les types générés côté front)
    "ENUM_NAME_OVERRIDES": {
        "UnitStatusEnum": "properties.models.Unit.STATUS_CHOICES",
        "LeaseStatusEnum": "leases.models.Contract.STATUS_CHOICES",
        "ListingStatusEnum": "listings.models.Listing.STATUS",
        "TicketStatusEnum": "maintenance.models.MaintenanceTicket.STATUS_CHOICES",
        "PriorityEnum": "maintenance.models.MaintenanceTicket.PRIORITY_CHOICES",
        "SubscriptionStatusEnum": "subscriptions.models.Subscription.STATUS",
        "NotificationStatusEnum": "notifications.models.Notification.STATUS",
        "UnitCategoryEnum": "properties.models.Unit.CATEGORY_CHOICES",
        "ListingTypeEnum": "listings.models.Listing.LISTING_TYPE",
        "UnitsRangeEnum": "public.models.DemoRequest.UNITS_RANGE",
    },
}

# CORS : origines du front autorisées à appeler l'API (ex. http://localhost:3000)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", "http://localhost:3000")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Fichiers envoyés (photos des annonces). Servis par Django uniquement en DEBUG :
# en production, les servir via le serveur web ou un stockage objet.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Sécurité en production (actif dès que DEBUG=False)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)


