# Generated by Django 6.0.8 on 2026-09-23 23:44

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(default=organizations.models.default_trial_end),
        ),
    ]
