# Generated by Django 6.0.8 on 2026-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
