# Generated by Django 6.0.8 on 2026-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
