# Generated by Django 6.0.8 on 2026-09-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_organization_alter_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.CharField(choices=[('APARTMENT', 'Appartement'), ('HOUSE', 'Maison / villa'), ('STUDIO', 'Studio'), ('OFFICE', 'Bureau'), ('SHOP', 'Local commercial'), ('LAND', 'Terrain')], default='APARTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
