# Generated by Django 6.0.8 on 2026-09-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='owner',
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
