# Generated by Django 6.0.8 on 2026-09-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('units_range', models.CharField(choices=[('1-20', '1-20'), ('21-100', '21-100'), ('101-500', '101-500'), ('500+', '500+')], max_length=10, verbose_name='nombre de lots gérés')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False, verbose_name='traitée')),
            ],
            options={
                'verbose_name': 'demande de démo',
                'verbose_name_plural': 'demandes de démo',
                'ordering': ['-created_at'],
            },
        ),
    ]
