# Generated by Django 6.0.1 on 2026-01-07 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='contract_type',
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salecontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salecontract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
