# Generated by Django 6.0.8 on 2026-09-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_remove_leasecontract_contract_type_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='salecontract',
            name='owner',
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salecontract',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salecontract',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
