# Generated by Django 6.0.8 on 2026-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercapability',
            name='access_user_context_7972f6_idx',
        ),
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.ManyToManyField(related_name='roles', through='access.RoleCapability', to='access.capability'),
        ),
        migrations.RemoveField(
            model_name='usercapability',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='usercapability',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='UserCapability',
        ),
    ]
