# Generated by Django 6.0.8 on 2026-09-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
