# Generated by Django 6.0.8 on 2026-09-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_automationrule_organization_and_more'),
        ('organizations', '0005_organization_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='kind',
            field=models.CharField(choices=[('VISIT_REQUEST', 'Demande de visite'), ('PAYMENT_RECEIVED', 'Paiement enregistré'), ('TICKET_CREATED', 'Ticket de maintenance'), ('TICKET_ASSIGNED', 'Ticket assigné'), ('RENT_OVERDUE', 'Loyer en retard'), ('LEASE_ENDING', 'Bail arrivant à échéance'), ('TRIAL_ENDING', "Fin d'essai"), ('DEMO_REQUEST', 'Demande de démo')], default='PAYMENT_RECEIVED', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inapp_notifications', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inapp_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_09cf3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='inappnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='inapp_unique_dedupe_per_user'),
        ),
    ]
